### ISSUE TITLE
Groupdocs Viewer - Trail Version

### ISSUE THREAD

**Issue by SriAzureDev** [groupdocs-free-consulting/display-document-in-browser-without-downloading#1]
I am using the group docs trail version and can view up to 2 pages due to the trail mode. How many days can I be able to view 2 pages with the trail version? is there any restriction for that or I can be able to view 2 pages with a trail version with no expiry?

**Comment by atirtahirgroupdocs** [comment]
@SriAzureDev Please have a look at API [evaluation limitations](https://docs.groupdocs.com/viewer/net/evaluation-limitations-and-licensing-of-groupdocs-viewer/). You will keep facing such a limitation until and unless API license is applied. In order to evaluate API features, you can request a temporary license [here](https://purchase.groupdocs.com/buy) that is actually a time-restricted full license. 
Please note, you could raise such issues at our free support [forum](http://forum.groupdocs.com/) and we'll further assist you there.

**Comment by Framework-Support** [comment]
@atirtahirgroupdocs THanks for your quick response.

I am looking out for an example with Angular having options of Search, View, Merge, download, navigate , add comments, print. It would be great if you can provide me such example. As the example with angular is little confusing from the groupdocs total angular.

**Comment by atirtahirgroupdocs** [comment]
@Framework-Support we already answered this query on [forum](https://forum.groupdocs.com/t/search-view-merge-download-navigate-add-comments-print-options/9043/3).

**Comment by SriAzureDev** [comment]
Hi,
It would be helpful if you can provide me clarification on below.

I have a requirement that my documents are stored in SQL server and i would like to implement full text search requirement, suppose - When i enter sample to search, it should go to SQL server and get me all the document names having “sample” in their file name and next it should search for all the file content having sample. Finally it should return the files in the order of having “Sample” in large count first followed by subsequent files.

Please let me know if this is possible with Groupdocs, if so please share me some sample to work with.

Thank you in advance.

**Comment by atirtahirgroupdocs** [comment]
@SriAzureDev 
We've already assisted this query on [forum](https://forum.groupdocs.com/t/search-view-merge-download-navigate-add-comments-print-options/9043/4?u=atir_tahir).
